FROM python:3.11-trixie

WORKDIR /josue_dir

COPY . .

RUN pip install --no-cache-dir -r requirements.txt

# RUN pip install psycopg2-binary

# RUN pip install python-dotenv

# RUN pip install streamlit

# CMD ["streamlit", "run", "/workspace/extract-workflow/app.py"]